### ISSUE TITLE
Non-JSON response sent by Push Endpoint

### ISSUE THREAD

**Issue by steffenweber** [mozilla-services/autopush#255]
I'm experimenting with the [W3C Push API](https://hacks.mozilla.org/2015/10/keep-pushing-it-with-the-w3c-push-api/) and Mozilla endpoints that start with:

```
https://updates.push.services.mozilla.com/push/...
```

I'm assuming this repository contains the server-side component. A comment in [endpoint.py](https://github.com/mozilla-services/autopush/blob/master/autopush/endpoint.py) says:

> All responses will be of the content-type `application/json` [...]

But a few hours ago I've received a plain-text response that just said:

`Notification Stored`

This is not valid JSON because the string is not quoted.

Is this a bug? Or am I getting something wrong?

**Comment by jrconlin** [comment]
Be default, autopush uses the older SimplePush spec (because we've got devices we need to support). With that spec, the content of the reply was ignored in favor of the return code (200 for immediate delivery, 202 for a notification that is stored waiting for the device to reconnect.) The body of the message didn't really matter.

Oddly, Firefox should be setting a "use_webpush" flag in the "hello" handshake, this should kick things over to using the WebPush protocol. Are you using Firefox or something else?

Thanks!

**Comment by kitcambridge** [comment]
@steffenweber Interesting! Was this a fresh endpoint that you created via `pushManager.subscribe()`? `use_webpush` was added in Firefox 43; something is afoot if you're seeing new endpoints that return text-only responses.

Side note: our endpoint handler also defaults to the Simple Push router if the UAID record doesn't include a `router_type` (https://github.com/mozilla-services/autopush/blob/master/autopush/endpoint.py#L626). I wonder if we can replace that with just `result.get("router_type")`, and return an error for incomplete records. What do you think, @bbangert?

**Comment by steffenweber** [comment]
I used Firefox Developer Edition 44.0a2 (2015-11-12) to create the subscription.

I'm not sure which "use_webpush" flag or "hello" handshake you are talking about. In the `pushManager.getSubscription()` callback in my client-side JavaScript code I send `subscription.endpoint` and `subscription.getKey('p256dh')` to my server. And now I want to send push notifications from my server to Firefox via the Mozilla servers (which works but sometimes I get strange responses like the one reported here). So after I've grabbed the endpoint URL + key, Firefox is not directly involved anymore from my perspective. What are the "use_webpush" flag or "hello" handshake?

If I understand you correctly then Firefox should have provided me with a different endpoint URL? I've just created a new subscription and Firefox has again provided me with an endpoint URL starting with `https://updates.push.services.mozilla.com/push/` followed by 184 Base64-like characters.

**Comment by steffenweber** [comment]
I've just found out that the "use_webpush" flag seems to concern the communication between Firefox and the Mozilla servers. I'm talking about the communication between the Mozilla servers and servers that send/submit push notifications. :smiley:

**Comment by jrconlin** [comment]
@steffenweber Ah, yeah, sorry. I live on the server, so I tend to think that's where the problems are. 
The normal endpoint we provide back is what you're seeing (`https://updates.push.services.mozilla.com/push/LongStringOfCrap123`)  The other bits I've noted is part of the magic between Firefox and our servers that you don't see. @kitcambridge is more versed in that part. 

As he notes, however, if there's a problem during that magic, it could produce the weirdness you're seeing. The fact that this is intermittent is also concerning.

**Comment by bbangert** [comment]
@steffenweber did repeat requests get the same thing? or was this a single one out of multiple requests to the same endpoint that got it?

**Comment by steffenweber** [comment]
It turns out that there is a specific push subscription where this issue happens every single time.

The response is:

```
HTTP/1.1 202 Accepted
Access-Control-Allow-Headers: content-encoding,encryption,encryption-key,content-type
Access-Control-Allow-Methods: POST,PUT
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: location
Content-Type: text/html; charset=UTF-8
Date: Sun, 22 Nov 2015 09:02:22 GMT
Server: cyclone/1.1
Content-Length: 19
Connection: keep-alive

Notification Stored
```

So the `Content-Type` header does not even claim that the response uses JSON. But it should use JSON, correct?

**Comment by bbangert** [comment]
Ah, that does matter quite a bit. What seems to have happened is the other Firefox registered in a way that doesn't let it get webpush data notifications. I'm not sure how/why this happened.

**Comment by kitcambridge** [comment]
Thanks, @steffenweber. A few more questions:

1. You've been able to create other subscriptions that return JSON responses using the same Firefox profile, right? It's just this one that's giving you trouble?
1. Any chance you remember when you created that subscription?
1. Could you please open `about:config`, and paste the value of the `dom.push.userAgentID` pref in this ticket?
1. Could you also paste the full endpoint?

Thanks!

**Comment by steffenweber** [comment]
Please excuse the late reply. I had to fend off some iditos DDoS'ing our website. :neutral_face:

I've just been given remote access to the user's computer. However, the installed Firefox 45 did not have an active push subscription (but to be honest, we are not completely sure that the profile has not been reset, the browser is used for testing purposes).

The subscription has worked at least once and was created on 2015-11-09. The endpoint URL is as follows: https://updates.push.services.mozilla.com/push/gAAAAABWQN88NQ7G8qsdLfwjvLOqfVqB0Of4Y-fN0GslqOb9sQN2eNRqVrk4b6ZNxomkZq2H1O8b9tNpiNf50pp3OKU4ro_JHU1vwDBgcTm36o1iK5T5yq5gplvNdVTApelkxI-JSWpP0bIbkJ4IPQ7SbYap6riQrRp09k77C7YP_bm5DJhcAdM=

```
$ curl -v -d "" https://updates.push.services.mozilla.com/push/gAAAAABWQN88NQ7G8qsdLfwjvLOqfVqB0Of4Y-fN0GslqOb9sQN2eNRqVrk4b6ZNxomkZq2H1O8b9tNpiNf50pp3OKU4ro_JHU1vwDBgcTm36o1iK5T5yq5gplvNdVTApelkxI-JSWpP0bIbkJ4IPQ7SbYap6riQrRp09k77C7YP_bm5DJhcAdM=
*   Trying 52.34.11.190...
* Connected to updates.push.services.mozilla.com (52.34.11.190) port 443 (#0)
* Initializing NSS with certpath: none
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* ALPN/NPN, server did not agree to a protocol
* SSL connection using TLS_DHE_RSA_WITH_AES_128_CBC_SHA
* Server certificate:
* 	subject: CN=push.services.mozilla.com,O=Mozilla Corporation,L=Mountain View,ST=California,C=US
* 	start date: Okt 29 00:00:00 2015 GMT
* 	expire date: Nov 02 12:00:00 2017 GMT
* 	common name: push.services.mozilla.com
* 	issuer: CN=DigiCert SHA2 Secure Server CA,O=DigiCert Inc,C=US
> POST /push/gAAAAABWQN88NQ7G8qsdLfwjvLOqfVqB0Of4Y-fN0GslqOb9sQN2eNRqVrk4b6ZNxomkZq2H1O8b9tNpiNf50pp3OKU4ro_JHU1vwDBgcTm36o1iK5T5yq5gplvNdVTApelkxI-JSWpP0bIbkJ4IPQ7SbYap6riQrRp09k77C7YP_bm5DJhcAdM= HTTP/1.1
> Host: updates.push.services.mozilla.com
> User-Agent: curl/7.45.0
> Accept: */*
> Content-Length: 0
> Content-Type: application/x-www-form-urlencoded
> 
< HTTP/1.1 201 Created
< Access-Control-Allow-Headers: content-encoding,encryption,encryption-key,content-type
< Access-Control-Allow-Methods: POST,PUT
< Access-Control-Allow-Origin: *
< Access-Control-Expose-Headers: location
< Content-Type: text/html; charset=UTF-8
< Date: Wed, 25 Nov 2015 22:21:05 GMT
< Server: cyclone/1.1
< TTL: 0
< Content-Length: 16
< Connection: keep-alive
< 
* Connection #0 to host updates.push.services.mozilla.com left intact
Finished Routing
```

Please notice the header `Content-Type: text/html; charset=UTF-8` and the non-JSON response body. I hope this helps you to debug this problem.

**Comment by bbangert** [comment]
Can you ensure the client is offline, and try it again? Same endpoint url and such.

**Comment by bbangert** [comment]
Offhand, I do see the bug in the lack of JSON response. It's in endpoint.py on line 431 of the router_response function, where it doesn't return a JSON wrapped response unless its an error code.

I'm much more curious about how this might've triggered a 202 for a webpush message.

Thanks for the detailed report!

**Comment by steffenweber** [comment]
> Can you ensure the client is offline, and try it again?

The browser has been closed. The response sent by the Mozilla servers remains the same.

**Comment by bbangert** [comment]
Ah good, that's what it should be. I'm curious how the prior profile got anything other than a 201.

**Comment by steffenweber** [comment]
Has this issue been fixed? I've just received an HTTP 404 response with the following body:

```
{"errno":103,"code":404,"error":"Not Found"}
```

**Comment by sinzeforever** [comment]
Hi there, just like to ask some question
I got  an 500 error with errorno 999  when I PUT my endpoint   https://updates.push.services.mozilla.com/push/gAAA.......
Is the server under some maintenance currently ? thanks

**Comment by steffenweber** [comment]
I've received those errors, too.

`{"errno":999,"code":500,"error":"Internal Server Error"}`

**Comment by bbangert** [comment]
This latest error response was indeed a bug, that has been fixed. Closing this as the prior error has not been reproduced since either, and we've had several updates since then that should've addressed it.

**Comment by steffenweber** [comment]
Since ~ 3 days I'm again seeing non-JSON `Notification Stored` responses.

**Comment by iveeshal** [comment]
Hey even I am getting non JSON response Finished Routing on
this endpoint

https://updates.push.services.mozilla.com/push/gAAAAABWwumTWVtt9g702f9AOkaoGExY-MuIvNkPLbFXkRTBa52CMEAKlDRg_AVkTBL33pHVo0OZsIdYHwvlLWhOnl9riVJ6bQ-s2L5p6iqIxSAkkgkp9zBS7Bgiqkv8_WBbVn1wdJIy2aQG2u4_b1w10dYX3ukO1NQn6DApnzNE70AAaXzaOpY=

**Comment by jrconlin** [comment]
Interesting. We're going to be adding a "Location" header to the response which will return information that will make it easier to figure out what's going on. (https://github.com/mozilla-services/autopush/pull/342). That's scheduled for rolling out this week unless we hit a problem on stage. 

We're still not 100% sure why these channels are being set as the older "simplepush" protocol, nor why it doesn't show up when we're doing load tests, but we're hoping that this will let us chase it down better.

Thanks!

**Comment by jrconlin** [comment]
The source of the problem was identified and resolved as part of https://github.com/mozilla-services/autopush/releases/tag/1.13.2

**Comment by steffenweber** [comment]
Thank you!
